import type {
  HostDistributionDiscoveryState,
  HostDistributionHandoffBridge,
  HostDistributionHost,
  HostDistributionMode,
  HostDistributionTarget,
  HostVerificationStatus,
} from '../../constants/index.js';

/**
 * Describes one canonical workflow asset tracked by the host-distribution registry.
 */
export interface StructuredWorkflowAssetRecord {
  workflowId: string;
  workflowVersion: string;
  workflowStatus: string;
  semanticOwnerModule: string;
  displayName: string;
  description: string;
  canonicalSourceRefs: string[];
  sourcePackRefs: string[];
  hostTargetMatrix: HostDistributionTarget[];
  triggerHints: string[];
  inputs: string[];
  artifacts: string[];
  riskTier: string;
  handoffBridge: HostDistributionHandoffBridge;
  handoffTarget: string;
  verificationProfileRefs: string[];
  driftChecks: string[];
}

/**
 * Defines the registry constructor payload.
 */
export interface StructuredWorkflowAssetRegistryOptions {
  records?: StructuredWorkflowAssetRecord[];
}

/**
 * Defines one projected file generated by the shared renderer.
 */
export interface HostExportProjectedFile {
  relativePath: string;
  content: string;
  workflowId: string;
  target: HostDistributionTarget;
  canonicalSourceRefs: string[];
  sourcePackRefs: string[];
  hostPath?: string;
  bundlePath?: string;
}

/**
 * Describes the capability envelope for one host target.
 */
export interface HostTargetCapabilities {
  host: HostDistributionHost;
  target: HostDistributionTarget;
  supportedModes: HostDistributionMode[];
  supportedDiscoveryStates: HostDistributionDiscoveryState[];
  supportedHandoffBridges: HostDistributionHandoffBridge[];
  supportsApplyToRepo: boolean;
  supportsBundlePackaging: boolean;
  isMvpTarget: boolean;
}

/**
 * Defines one verification row emitted by host-distribution validation.
 */
export interface HostVerificationCheck {
  checkId: string;
  status: HostVerificationStatus;
  detail: string;
  inspectedPath?: string;
  expectedValue?: string;
  actualValue?: string;
}

/**
 * Defines the summary output of host-distribution verification.
 */
export interface HostVerificationSummary {
  schemaVersion: string;
  status: HostVerificationStatus;
  verifiedAt: string;
  verificationSummaryPath: string;
  exportManifestPath: string;
  checks: HostVerificationCheck[];
  inspectedPaths: string[];
  driftDetected: boolean;
}

/**
 * Defines the structured renderer input consumed by the registry service.
 */
export interface HostRendererRenderInput {
  host: HostDistributionHost;
  mode: HostDistributionMode;
  target: HostDistributionTarget;
  stagedExportRoot: string;
  exportManifestPath: string;
  verificationSummaryPath: string;
  canonicalSourceRefs?: string[];
  sourcePackRefs?: string[];
  workflowIds?: string[];
  discoveryState?: HostDistributionDiscoveryState;
  handoffBridge?: HostDistributionHandoffBridge;
  applyRoot?: string;
  applyReportPath?: string;
  bundleRoot?: string;
  packReportPath?: string;
}

/**
 * Defines the renderer result returned by the shared registry service.
 */
export interface HostRendererRenderResult {
  renderedAt: string;
  exportManifest: HostExportManifest;
  projectedFiles: HostExportProjectedFile[];
  verificationSummary: HostVerificationSummary;
  applyReport?: HostApplyReport;
  packReport?: HostPackReport;
}

/**
 * Defines the canonical export manifest for host-distribution staging.
 */
export interface HostExportManifest {
  schemaVersion: string;
  generatedAt: string;
  host: HostDistributionHost;
  mode: HostDistributionMode;
  target: HostDistributionTarget;
  stagedExportRoot: string;
  discoveryState: HostDistributionDiscoveryState;
  semanticOwnerModule: string;
  canonicalSourceRefs: string[];
  sourcePackRefs: string[];
  workflowIds: string[];
  exportManifestPath: string;
  applyReportPath?: string;
  packReportPath?: string;
  handoffBridge: HostDistributionHandoffBridge;
  targetCapabilities: HostTargetCapabilities;
  projectedFiles: HostExportProjectedFile[];
  verificationSummary: HostVerificationSummary;
}

/**
 * Defines the report emitted after staged assets are applied into a repository.
 */
export interface HostApplyReport {
  schemaVersion: string;
  appliedAt: string;
  host: HostDistributionHost;
  mode: HostDistributionMode;
  target: HostDistributionTarget;
  stagedExportRoot: string;
  applyRoot: string;
  discoveryState: HostDistributionDiscoveryState;
  applyReportPath: string;
  exportManifestPath: string;
  appliedFiles: HostExportProjectedFile[];
  skippedFiles: HostExportProjectedFile[];
  status: HostVerificationStatus;
  verificationSummary: HostVerificationSummary;
}

/**
 * Defines the report emitted after staged assets are packaged for host installation.
 */
export interface HostPackReport {
  schemaVersion: string;
  packedAt: string;
  host: HostDistributionHost;
  mode: HostDistributionMode;
  target: HostDistributionTarget;
  stagedExportRoot: string;
  bundleRoot: string;
  discoveryState: HostDistributionDiscoveryState;
  packReportPath: string;
  exportManifestPath: string;
  packedFiles: HostExportProjectedFile[];
  status: HostVerificationStatus;
  verificationSummary: HostVerificationSummary;
}
