export {
  SQLITE_FS_ARCHIVE_TABLE_NAME,
  SQLITE_FS_DATABASE_FILE_NAME,
  SQLITE_FS_RECORDS_TABLE_NAME,
  SQLITE_FS_SNAPSHOTS_DIRECTORY_NAME,
  SQLITE_FS_SNAPSHOTS_TABLE_NAME,
} from "./sqlite-fs-memory-store.constant.js";
