export {
  DesktopArtifactQueryGateState,
  DesktopOrchestrationRuntimeMode,
  DESKTOP_ARTIFACT_PANE_DEFERRED_REASON,
  DESKTOP_CONSOLE_DEFAULT_EXECUTION_LIMIT,
  DESKTOP_SESSION_BRIDGE_OPERATIONS,
  DESKTOP_SHELL_COMPONENT_OWNERS,
  DESKTOP_SHELL_PACKAGE_NAME,
} from './desktop.constant.js';
