export const LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_DRAFT_SCHEMA_VERSION =
  'local_orchestration_workflow_draft_session_v1';
export const LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_DEFINITION_SCHEMA_VERSION =
  'cli_workflow_definition_v1';
export const LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_DIRECTORY_SEGMENTS = [
  'context',
  'workflow',
] as const;
export const LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_DRAFT_DIRECTORY_SEGMENTS = [
  ...LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_DIRECTORY_SEGMENTS,
  'draft-sessions',
] as const;
export const LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_DEFINITION_FILE_NAME =
  'active-workflow.definition.json';
export const LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_DRAFT_FILE_NAME = 'direct-workbench.active.json';
export const LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_DEFAULT_TEMPLATE_ID = 'parallel-review';
export const LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_MISSING_BASE_DEFINITION_REVISION =
  'workspace-definition:missing';
export const LOCAL_ORCHESTRATION_SERVICE_WORKFLOW_EDITOR_ISSUE_CODE = {
  CONDITION_BRANCH_REQUIRED: 'CONDITION_BRANCH_REQUIRED',
  CONDITION_BRANCH_KEY_REQUIRED: 'CONDITION_BRANCH_KEY_REQUIRED',
  CONDITION_BRANCH_DUPLICATED: 'CONDITION_BRANCH_DUPLICATED',
} as const;
