/**
 * Defines environment keys consumed by CLI notification-provider assembly.
 */
export enum CliNotificationProviderEnvironmentKey {
  WEBHOOK_URL = "REPO_AI_GOVERNOR_NOTIFICATION_WEBHOOK_URL",
  WEBHOOK_AUTH_TOKEN = "REPO_AI_GOVERNOR_NOTIFICATION_WEBHOOK_AUTH_TOKEN",
  WEBHOOK_HEADERS_JSON = "REPO_AI_GOVERNOR_NOTIFICATION_WEBHOOK_HEADERS_JSON",
  WEBHOOK_TIMEOUT_MS = "REPO_AI_GOVERNOR_NOTIFICATION_WEBHOOK_TIMEOUT_MS",
  WEBHOOK_BACKOFF_BASE_MS = "REPO_AI_GOVERNOR_NOTIFICATION_WEBHOOK_BACKOFF_BASE_MS",
  CHAT_IM_URL = "REPO_AI_GOVERNOR_NOTIFICATION_CHAT_IM_URL",
  CHAT_IM_AUTH_TOKEN = "REPO_AI_GOVERNOR_NOTIFICATION_CHAT_IM_AUTH_TOKEN",
  CHAT_IM_HEADERS_JSON = "REPO_AI_GOVERNOR_NOTIFICATION_CHAT_IM_HEADERS_JSON",
  CHAT_IM_TIMEOUT_MS = "REPO_AI_GOVERNOR_NOTIFICATION_CHAT_IM_TIMEOUT_MS",
  CHAT_IM_BACKOFF_BASE_MS = "REPO_AI_GOVERNOR_NOTIFICATION_CHAT_IM_BACKOFF_BASE_MS",
}
