export type {
  Locale,
  AdapterInputSource,
  AdapterOutputArtifact,
  MainstreamAdapterId,
  AdapterType,
  AdapterEntrypoint,
  AdapterProtocol,
  AdapterRequiredView,
  AdapterSupportedFormat,
  AdapterInjectionMode,
  AdapterInjectionSource,
  AdapterPresetMap,
  SlotConflictPolicy,
  GenericRecord,
  ResolvedConfigState,
  BuildClaudeCodeAdapterBundleOptions,
  BuildCodexAdapterBundleOptions,
  BuildGitHubCopilotAdapterBundleOptions,
} from "./aliases/index.js";
export type {
  LocaleOptions,
  AdapterDefinition,
  AdapterLocalizedText,
  AdapterRuntimeConfig,
  OptionalFileState,
  ArtifactPaths,
  StandardsSectionItem,
  SlotSummaryActiveItem,
  SlotSummaryInjections,
  SlotSummaryChecks,
  SlotSummary,
  AdapterBundleEntryFile,
  AdapterBundleEntry,
  AdapterBundleReferences,
  AdapterBaseBundle,
  BuildBaseAdapterBundleOptions,
  AdapterPromptFile,
  ClaudeCodeAdapterBundleFiles,
  ClaudeCodeAdapterBundle,
  CodexAdapterBundle,
  GitHubCopilotAdapterBundleFiles,
  GitHubCopilotAdapterBundle,
} from "./interfaces/index.js";
