import { CliReactThemePreset } from '../../constants/cli-react-theme.constant.js';
import type { ReactCliThemeDefinition } from '../../types/index.js';
import { createReactCliThemeDefinition } from './react-cli-theme-factory.js';

/**
 * Stores the concrete palette definitions for every supported React CLI theme preset.
 */
export const REACT_CLI_THEME_PRESET_REGISTRY: Record<CliReactThemePreset, ReactCliThemeDefinition> =
  {
    [CliReactThemePreset.GOVERNOR]: createReactCliThemeDefinition(
      CliReactThemePreset.GOVERNOR,
      {
        borderColor: '#5E81AC',
        titleColor: '#88C0D0',
        subtitleColor: '#81A1C1',
        attentionColor: '#EBCB8B',
        sectionTitleColor: '#ECEFF4',
        helpColor: '#A7B4C4',
        footerColor: '#8FBCBB',
        promptTitleColor: '#88C0D0',
        conversationPalette: {
          assistantTextColor: '#ECEFF4',
          assistantHeadingColor: '#88C0D0',
          assistantQuoteColor: '#81A1C1',
          assistantCodeColor: '#88C0D0',
          userBubbleBorderColor: '#8FBCBB',
          userTextColor: '#ECEFF4',
        },
        liveActivityPalette: {
          borderColor: '#5E81AC',
          titleColor: '#A7B4C4',
          summaryColor: '#88C0D0',
          bulletColor: '#A7B4C4',
          primaryTextColor: '#ECEFF4',
          secondaryTextColor: '#A7B4C4',
          systemTextColor: '#81A1C1',
          errorTextColor: '#EBCB8B',
          tagPalette: {
            neutral: '#81A1C1',
            system: '#4C566A',
            role: '#5E81AC',
            running: '#88C0D0',
            completed: '#A3BE8C',
            todo: '#EBCB8B',
            error: '#BF616A',
          },
        },
      },
      {
        info: '#5E81AC',
        success: '#A3BE8C',
        warning: '#EBCB8B',
        error: '#BF616A',
        focus: '#88C0D0',
        selected: '#A3BE8C',
        input: '#E5E9F0',
      },
    ),
    [CliReactThemePreset.COPILOT]: createReactCliThemeDefinition(
      CliReactThemePreset.COPILOT,
      {
        borderColor: '#3B82F6',
        titleColor: '#E5F0FF',
        subtitleColor: '#8BA7D9',
        attentionColor: '#F2C94C',
        sectionTitleColor: '#F7FAFF',
        helpColor: '#94A3B8',
        footerColor: '#7DD3FC',
        promptTitleColor: '#60A5FA',
        conversationPalette: {
          assistantTextColor: '#E5F0FF',
          assistantHeadingColor: '#60A5FA',
          assistantQuoteColor: '#8BA7D9',
          assistantCodeColor: '#93C5FD',
          userBubbleBorderColor: '#38BDF8',
          userTextColor: '#E5F0FF',
        },
        liveActivityPalette: {
          borderColor: '#3B82F6',
          titleColor: '#9DB6DE',
          summaryColor: '#60A5FA',
          bulletColor: '#94A3B8',
          primaryTextColor: '#E5F0FF',
          secondaryTextColor: '#94A3B8',
          systemTextColor: '#7C93BF',
          errorTextColor: '#F87171',
          tagPalette: {
            neutral: '#94A3B8',
            system: '#1E293B',
            role: '#3B82F6',
            running: '#60A5FA',
            completed: '#34D399',
            todo: '#FBBF24',
            error: '#F87171',
          },
        },
      },
      {
        info: '#3B82F6',
        success: '#34D399',
        warning: '#FBBF24',
        error: '#F87171',
        focus: '#60A5FA',
        selected: '#34D399',
        input: '#E5F0FF',
      },
    ),
    [CliReactThemePreset.CATPPUCCIN]: createReactCliThemeDefinition(
      CliReactThemePreset.CATPPUCCIN,
      {
        borderColor: '#8AADF4',
        titleColor: '#C6A0F6',
        subtitleColor: '#939AB7',
        attentionColor: '#EED49F',
        sectionTitleColor: '#CAD3F5',
        helpColor: '#A5ADCB',
        footerColor: '#F5BDE6',
        promptTitleColor: '#8AADF4',
        conversationPalette: {
          assistantTextColor: '#CAD3F5',
          assistantHeadingColor: '#C6A0F6',
          assistantQuoteColor: '#939AB7',
          assistantCodeColor: '#8AADF4',
          userBubbleBorderColor: '#F5BDE6',
          userTextColor: '#CAD3F5',
        },
        liveActivityPalette: {
          borderColor: '#8AADF4',
          titleColor: '#A5ADCB',
          summaryColor: '#C6A0F6',
          bulletColor: '#A5ADCB',
          primaryTextColor: '#CAD3F5',
          secondaryTextColor: '#A5ADCB',
          systemTextColor: '#939AB7',
          errorTextColor: '#ED8796',
          tagPalette: {
            neutral: '#939AB7',
            system: '#6E738D',
            role: '#91A6D9',
            running: '#8AADF4',
            completed: '#A6DA95',
            todo: '#EED49F',
            error: '#ED8796',
          },
        },
      },
      {
        info: '#8AADF4',
        success: '#A6DA95',
        warning: '#EED49F',
        error: '#ED8796',
        focus: '#C6A0F6',
        selected: '#A6DA95',
        input: '#CAD3F5',
      },
    ),
    [CliReactThemePreset.CALM]: createReactCliThemeDefinition(
      CliReactThemePreset.CALM,
      {
        borderColor: '#9CCFD8',
        titleColor: '#C4A7E7',
        subtitleColor: '#908CAA',
        attentionColor: '#F6C177',
        sectionTitleColor: '#E0DEF4',
        helpColor: '#908CAA',
        footerColor: '#9CCFD8',
        promptTitleColor: '#EBBCBA',
        conversationPalette: {
          assistantTextColor: '#E0DEF4',
          assistantHeadingColor: '#C4A7E7',
          assistantQuoteColor: '#908CAA',
          assistantCodeColor: '#EBBCBA',
          userBubbleBorderColor: '#9CCFD8',
          userTextColor: '#E0DEF4',
        },
        liveActivityPalette: {
          borderColor: '#9CCFD8',
          titleColor: '#908CAA',
          summaryColor: '#C4A7E7',
          bulletColor: '#908CAA',
          primaryTextColor: '#E0DEF4',
          secondaryTextColor: '#908CAA',
          systemTextColor: '#6E6A86',
          errorTextColor: '#EB6F92',
          tagPalette: {
            neutral: '#908CAA',
            system: '#6E6A86',
            role: '#9CB4D8',
            running: '#9CCFD8',
            completed: '#31748F',
            todo: '#F6C177',
            error: '#EB6F92',
          },
        },
      },
      {
        info: '#9CCFD8',
        success: '#31748F',
        warning: '#F6C177',
        error: '#EB6F92',
        focus: '#C4A7E7',
        selected: '#31748F',
        input: '#E0DEF4',
      },
    ),
    [CliReactThemePreset.TOKYO_NIGHT]: createReactCliThemeDefinition(
      CliReactThemePreset.TOKYO_NIGHT,
      {
        borderColor: '#82AAFF',
        titleColor: '#C099FF',
        subtitleColor: '#828BB8',
        attentionColor: '#FFC777',
        sectionTitleColor: '#C8D3F5',
        helpColor: '#737AA2',
        footerColor: '#86E1FC',
        promptTitleColor: '#89DDFF',
        conversationPalette: {
          assistantTextColor: '#C8D3F5',
          assistantHeadingColor: '#C099FF',
          assistantQuoteColor: '#828BB8',
          assistantCodeColor: '#89DDFF',
          userBubbleBorderColor: '#86E1FC',
          userTextColor: '#C8D3F5',
        },
        liveActivityPalette: {
          borderColor: '#82AAFF',
          titleColor: '#737AA2',
          summaryColor: '#C099FF',
          bulletColor: '#737AA2',
          primaryTextColor: '#C8D3F5',
          secondaryTextColor: '#828BB8',
          systemTextColor: '#636DA6',
          errorTextColor: '#FF757F',
          tagPalette: {
            neutral: '#737AA2',
            system: '#394B70',
            role: '#3E68D7',
            running: '#82AAFF',
            completed: '#C3E88D',
            todo: '#FFC777',
            error: '#FF757F',
          },
        },
      },
      {
        info: '#82AAFF',
        success: '#C3E88D',
        warning: '#FFC777',
        error: '#FF757F',
        focus: '#C099FF',
        selected: '#C3E88D',
        input: '#C8D3F5',
      },
    ),
    [CliReactThemePreset.KANAGAWA]: createReactCliThemeDefinition(
      CliReactThemePreset.KANAGAWA,
      {
        borderColor: '#7E9CD8',
        titleColor: '#E6C384',
        subtitleColor: '#727169',
        attentionColor: '#FF9E3B',
        sectionTitleColor: '#DCD7BA',
        helpColor: '#A6A69C',
        footerColor: '#7AA89F',
        promptTitleColor: '#7FB4CA',
        conversationPalette: {
          assistantTextColor: '#DCD7BA',
          assistantHeadingColor: '#E6C384',
          assistantQuoteColor: '#727169',
          assistantCodeColor: '#7FB4CA',
          userBubbleBorderColor: '#7AA89F',
          userTextColor: '#DCD7BA',
        },
        liveActivityPalette: {
          borderColor: '#7E9CD8',
          titleColor: '#A6A69C',
          summaryColor: '#E6C384',
          bulletColor: '#A6A69C',
          primaryTextColor: '#DCD7BA',
          secondaryTextColor: '#A6A69C',
          systemTextColor: '#727169',
          errorTextColor: '#E46876',
          tagPalette: {
            neutral: '#A6A69C',
            system: '#54546D',
            role: '#7E9CD8',
            running: '#7FB4CA',
            completed: '#98BB6C',
            todo: '#E6C384',
            error: '#E46876',
          },
        },
      },
      {
        info: '#7E9CD8',
        success: '#98BB6C',
        warning: '#E6C384',
        error: '#E46876',
        focus: '#957FB8',
        selected: '#98BB6C',
        input: '#DCD7BA',
      },
    ),
    [CliReactThemePreset.FLEXOKI]: createReactCliThemeDefinition(
      CliReactThemePreset.FLEXOKI,
      {
        borderColor: '#575653',
        titleColor: '#E6E4D9',
        subtitleColor: '#878580',
        attentionColor: '#DA702C',
        sectionTitleColor: '#FFFCF0',
        helpColor: '#878580',
        footerColor: '#3AA99F',
        promptTitleColor: '#4385BE',
        conversationPalette: {
          assistantTextColor: '#CECDC3',
          assistantHeadingColor: '#8B7EC8',
          assistantQuoteColor: '#878580',
          assistantCodeColor: '#4385BE',
          userBubbleBorderColor: '#3AA99F',
          userTextColor: '#CECDC3',
        },
        liveActivityPalette: {
          borderColor: '#575653',
          titleColor: '#878580',
          summaryColor: '#E6E4D9',
          bulletColor: '#878580',
          primaryTextColor: '#CECDC3',
          secondaryTextColor: '#878580',
          systemTextColor: '#6F6E69',
          errorTextColor: '#D14D41',
          tagPalette: {
            neutral: '#878580',
            system: '#575653',
            role: '#4385BE',
            running: '#3AA99F',
            completed: '#879A39',
            todo: '#D0A215',
            error: '#D14D41',
          },
        },
      },
      {
        info: '#4385BE',
        success: '#879A39',
        warning: '#D0A215',
        error: '#D14D41',
        focus: '#8B7EC8',
        selected: '#879A39',
        input: '#CECDC3',
      },
    ),
  };
