export enum GovernorErrorCode {
  UNKNOWN = "UNKNOWN",
  CONFIG_FILE_READ_FAILED = "CONFIG_FILE_READ_FAILED",
  CONFIG_FILE_PARSE_FAILED = "CONFIG_FILE_PARSE_FAILED",
  CONFIG_SCHEMA_VALIDATION_FAILED = "CONFIG_SCHEMA_VALIDATION_FAILED",
  CONFIG_PROFILE_NOT_FOUND = "CONFIG_PROFILE_NOT_FOUND",
  I18N_RUNTIME_ENGINE_UNSUPPORTED = "I18N_RUNTIME_ENGINE_UNSUPPORTED",
  I18N_RUNTIME_NOT_INITIALIZED = "I18N_RUNTIME_NOT_INITIALIZED",
}
