export type {
  MemoryProviderBuiltInDescriptor,
  MemoryProviderCompositionSummary,
  MemoryProviderConstructor,
  MemoryProviderInstanceOptions,
  MemoryProviderPluginDescriptor,
  MemoryProviderPluginFactory,
  MemoryProviderPluginLoadContext,
  MemoryProviderPluginPolicy,
  MemoryProviderRegistryResolutionResult,
  MemoryProviderResolvedDescriptor,
  MemoryProviderRegistryLoadRequest,
  MemoryProviderRegistryLoadResult,
  MemoryProviderRegistryOptions,
} from './memory-provider-registry.interface.js';
