export type {
  DesktopArtifactPaneCollectionViewModel,
  DesktopArtifactPaneEntryViewModel,
  DesktopArtifactPaneViewModel,
  DesktopExecutionBoardEntryViewModel,
  DesktopOrchestrationServiceOwner,
  DesktopOrchestrationServiceOwnerContext,
  DesktopOrchestrationServiceRuntimeDependencies,
  DesktopLifecycleSnapshot,
  DesktopShellBaseline,
  DesktopShellBootstrapSnapshot,
  DesktopExecutionTimelineEntryViewModel,
  DesktopGovernanceActionBuildInput,
  DesktopGovernanceActionViewModel,
  DesktopGovernanceConsoleBuildOptions,
  DesktopGovernanceConsoleCollectionViewModel,
  DesktopGovernanceParallelLaneViewModel,
  DesktopGovernanceQueueEntryViewModel,
  DesktopGovernanceQueueOverviewViewModel,
  DesktopGovernanceConsoleSectionViewModel,
  DesktopGovernanceConsoleViewModel,
  DesktopGovernanceWorkspaceSummaryViewModel,
  DesktopHandoffTargetBuildInput,
  DesktopHandoffTargetViewModel,
  DesktopHitlInboxEntryViewModel,
  DesktopPreloadBridgeApi,
  DesktopShellBootstrapDependencies,
} from './interfaces/index.js';
