export type {
  DesktopArtifactPaneCollectionViewModel,
  DesktopArtifactPaneEntryViewModel,
  DesktopArtifactPaneViewModel,
  DesktopOrchestrationServiceOwner,
  DesktopOrchestrationServiceRuntimeDependencies,
  DesktopLifecycleSnapshot,
  DesktopShellBaseline,
  DesktopShellBootstrapSnapshot,
  DesktopExecutionTimelineEntryViewModel,
  DesktopGovernanceConsoleBuildOptions,
  DesktopGovernanceConsoleSectionViewModel,
  DesktopGovernanceConsoleViewModel,
  DesktopPreloadBridgeApi,
  DesktopShellBootstrapDependencies,
} from './interfaces/index.js';
